load("//buck2:haskell.bzl", "haskell_test")
load("@third-party//haskell:tools.bzl", "GHC_BIN_DIR")

haskell_test(
    name = "glean-snapshot-codemarkup-haskell",
    main = "Main",
    srcs = [
        "Main.hs",
    ],
    deps = [
        "//glean/lang/haskell:haskell-indexer",
        "//glean/test/regression:regression-test-lib",
    ],
    test_args = [
        "--hie-indexer=$(exe //glean/lang/haskell:hie-indexer)",
    ],
    test_env = {
        "PATH": GHC_BIN_DIR + ":/usr/bin:/bin",
    },
    visibility = ["PUBLIC"],
)
