load("//buck2:haskell.bzl", "haskell_binary", "haskell_library")

haskell_library(
    name = "haskell-indexer",
    srcs = [
        "Glean/Indexer/Haskell.hs",
    ],
    deps = [
        "@hsthrift//common/util:fb-util",
        "//glean/index:indexer-core",
    ],
    packages = [
        "directory",
        "filepath",
        "optparse-applicative",
        "process",
    ],
    visibility = ["PUBLIC"],
)

haskell_binary(
    name = "hie-indexer",
    main = "HieIndexer.Main",
    srcs = [
        "HieIndexer/Main.hs",
        "HieIndexer/Index.hs",
        "HieIndexer/Options.hs",
    ],
    deps = [
        "@hsthrift//common/util:fb-util",
        "@hsthrift//lib:thrift-lib",
        "//glean/client/hs:client-hs",
        "//glean/client/hs/local:client-hs-local",
        "//glean/hs:core",
        "//glean/lib:lib",
        "//glean/github:stubs",
        "//glean/util:util",
        "//glean/schema/thrift:builtin",
        "//glean/schema/thrift:hs",
        "//glean/schema/thrift:src",
        "//glean/schema/hs:hs",
        "//glean/schema/hs:src",
    ],
    packages = [
        "ghc",
        "hie-compat",
        "hiedb",
    ],
    visibility = ["PUBLIC"],
)
