load("//buck2:haskell.bzl", "haskell_library")

haskell_library(
    name = "java-lsif-indexer",
    srcs = [
        "Glean/Indexer/JavaLsif.hs",
    ],
    deps = [
        "@hsthrift//common/util:fb-util",
        "//glean/index:indexer-core",
        "//glean/lang/lsif:lsif",
        "//glean/lang/lsif/indexer:lsif-indexer",
    ],
    packages = [
        "optparse-applicative",
    ],
    visibility = ["PUBLIC"],
)
