-- @generated
module Glean.Schema.Hack (allPredicates) where

import Glean.Types

allPredicates :: [(PredicateRef, Int)]
allPredicates =
  [ (PredicateRef "hack.ClassDeclaration" 4, 493)
  , (PredicateRef "hack.QName" 4, 485)
  , (PredicateRef "hack.TargetUses" 4, 479)
  , (PredicateRef "hack.filename" 1, 470)
  , (PredicateRef "hack.TargetUsesAbs" 4, 464)
  , (PredicateRef "hack.TraitDefinition" 4, 424)
  , (PredicateRef "hack.DeclarationName" 4, 409)
  , (PredicateRef "hack.FunctionDefinition" 4, 402)
  , (PredicateRef "hack.PropertyDeclaration" 4, 397)
  , (PredicateRef "hack.PropertyDefinition" 4, 366)
  , (PredicateRef "hack.ContainerChild" 4, 357)
  , (PredicateRef "hack.symbolNamespace" 1, 350)
  , (PredicateRef "hack.UserAttribute" 4, 346)
  , (PredicateRef "hack.DeclarationSource" 4, 341)
  , (PredicateRef "hack.NamespaceQName" 4, 333)
  , (PredicateRef "hack.InterfaceDeclaration" 4, 332)
  , (PredicateRef "hack.kind" 1, 330)
  , (PredicateRef "hack.InterfaceDefinition" 4, 315)
  , (PredicateRef "hack.Comment" 4, 298)
  , (PredicateRef "hack.identifier" 1, 297)
  , (PredicateRef "hack.NamespaceMember" 4, 286)
  , (PredicateRef "hack.ContainerParent" 4, 275)
  , (PredicateRef "hack.GlobalConstDefinition" 4, 273)
  , (PredicateRef "hack.EnumDefinition" 4, 265)
  , (PredicateRef "hack.symbol" 1, 264)
  , (PredicateRef "hack.ClassConstDefinition" 4, 261)
  , (PredicateRef "hack.GlobalConstDeclaration" 4, 255)
  , (PredicateRef "hack.DeclarationTarget" 4, 230)
  , (PredicateRef "hack.FileXRefs" 4, 215)
  , (PredicateRef "hack.DeclarationSpan" 4, 212)
  , (PredicateRef "hack.Enumerator" 4, 195)
  , (PredicateRef "hack.Signature" 4, 189)
  , (PredicateRef "hack.TypedefDeclaration" 4, 184)
  , (PredicateRef "hack.Name" 4, 183)
  , (PredicateRef "hack.MethodDeclaration" 4, 165)
  , (PredicateRef "hack.TraitDeclaration" 4, 148)
  , (PredicateRef "hack.FunctionDeclaration" 4, 141)
  , (PredicateRef "hack.MethodDefinition" 4, 122)
  , (PredicateRef "hack.FileDeclarations" 4, 103)
  , (PredicateRef "hack.DeclarationLocation" 4, 97)
  , (PredicateRef "hack.TypeConstDeclaration" 4, 96)
  , (PredicateRef "hack.NameLowerCase" 4, 57)
  , (PredicateRef "hack.TypeConstDefinition" 4, 53)
  , (PredicateRef "hack.Type" 4, 50)
  , (PredicateRef "hack.DeclarationComment" 4, 43)
  , (PredicateRef "hack.ClassConstDeclaration" 4, 34)
  , (PredicateRef "hack.EnumDeclaration" 4, 27)
  , (PredicateRef "hack.NamespaceDeclaration" 4, 19)
  , (PredicateRef "hack.ClassDefinition" 4, 1)
  ]

