load("//buck2:haskell.bzl", "haskell_library")

# Cabal's `indexers` library includes this module (Glean.Indexer.Swift)
# among its 18 - see glean/index/BUCK's comment for the split rationale.
haskell_library(
    name = "swift-indexer",
    srcs = [
        "Glean/Indexer/Swift.hs",
    ],
    deps = [
        "@hsthrift//common/util:fb-util",
        "@hsthrift//lib:thrift-lib",
        "//glean/client/hs:client-hs",
        "//glean/client/hs/local:client-hs-local",
        "//glean/index:indexer-core",
        "//glean/lang/scip:scip",
        "//glean/lang/scip/indexer:scip-indexer",
    ],
    packages = [
        "bytestring",
        "filepath",
        "optparse-applicative",
    ],
    visibility = ["PUBLIC"],
)
