load("//buck2:haskell.bzl", "haskell_binary")

haskell_binary(
    name = "glean",
    main = "GleanCLI",
    # -ltinfo: haskeline/terminfo (pulled in by glean/shell's interactive
    # REPL) call into libtinfo's terminal-capability functions
    # (set_curterm, tigetstr, tparm, ...) directly. A dynamic link resolves
    # this for free (haskeline's own .so already records libtinfo as a
    # DT_NEEDED dependency), but this migration's `opt` mode links
    # statically, and the third-party/haskell/BUCK generator
    # (buck2/gen-haskell-prebuilt.py) doesn't currently carry over a prebuilt
    # package's own `extra-libraries-static:` from its real GHC package
    # conf, so nothing else declares this dependency.
    linker_flags = ["-with-rtsopts=-I0", "-ltinfo"],
    srcs = [
        "GleanCLI.hs",
        "GleanCLI/Backup.hs",
        "GleanCLI/Common.hs",
        "GleanCLI/Complete.hs",
        "GleanCLI/Create.hs",
        "GleanCLI/Derive.hs",
        "GleanCLI/Finish.hs",
        "GleanCLI/Merge.hs",
        "GleanCLI/Index.hs",
        "GleanCLI/Query.hs",
        "GleanCLI/Restore.hs",
        "GleanCLI/WaitForWrites.hs",
        "GleanCLI/Write.hs",
    ],
    deps = [
        "@hsthrift//common/util:fb-util",
        "@hsthrift//lib:thrift-lib",
        "//glean/tools/gleancli/plugin:cli-types",
        "//glean/client/hs:client-hs",
        "//glean/client/hs/local:client-hs-local",
        "//glean/github:aclknobs",
        "//glean/db:db",
        "//glean/if:if-glean-hs",
        "//glean/index:indexer-core",
        "//glean/index/list:indexers",
        "//glean/shell:shell-lib",
        "//glean/github:stubs",
        "//glean/config:config",
        "//glean/hs:core",
        "//glean/lib:lib-derive",
        "//glean/util:util",
        "//glean/write:write",
    ],
    packages = [
        "aeson",
        "async",
        "bytestring",
        "containers",
        "data-default",
        "directory",
        "extra",
        "filepath",
        "Glob",
        "json",
        "process",
        "safe-exceptions",
        "split",
        "text",
        "time",
        "unordered-containers",
    ],
    visibility = ["PUBLIC"],
)
