load("//buck2:haskell.bzl", "haskell_binary")

# Cabal's `glean-snapshot-flow` test-suite (glean.cabal.in).
haskell_binary(
    name = "glean-snapshot-flow",
    main = "Glean.Regression.Flow.Main",
    srcs = [
        "Glean/Regression/Flow/Main.hs",
    ],
    deps = [
        "//glean/lang/flow:flow-indexer",
        "//glean/test/regression:regression-test-lib",
    ],
    visibility = ["PUBLIC"],
)
