load("//buck2:haskell.bzl", "haskell_binary")

# Cabal's `glean-snapshot-rust-scip` test-suite (glean.cabal.in).
haskell_binary(
    name = "glean-snapshot-rust-scip",
    main = "Glean.Regression.RustScip.Main",
    srcs = [
        "Glean/Regression/RustScip/Main.hs",
    ],
    deps = [
        "//glean/lang/rust-scip:rust-scip-indexer",
        "//glean/test/regression:regression-test-lib",
    ],
    visibility = ["PUBLIC"],
)
