load("//buck2:haskell.bzl", "haskell_library")

haskell_library(
    name = "hack-indexer",
    srcs = [
        "Glean/Indexer/Hack.hs",
    ],
    deps = [
        "@hsthrift//common/util:fb-util",
        "//glean/index:indexer-core",
    ],
    packages = [
        "optparse-applicative",
    ],
    visibility = ["PUBLIC"],
)
