load("@prelude//toolchains:demo.bzl", "system_demo_toolchains")
load("@toolchains//haskell.bzl", "haskell_toolchain")

# Defaults for other toolchains
system_demo_toolchains()

haskell_toolchain(
    name = "haskell",
    compiler = "ghc-9.4.8",
    packager = "ghc-pkg-9.4.8",
    haddock = "haddock",
    compiler_flags = ["-O"],
    linker_flags = [],
    visibility = ["PUBLIC"],
)
