load("//buck2:haskell.bzl", "haskell_binary")

# Cabal's `glass-server` executable (glean.cabal.in).
haskell_binary(
    name = "glass-server",
    main = "Server",
    srcs = [
        "Server.hs",
    ],
    deps = [
        "//glean/glass:glass-lib",
    ],
    visibility = ["PUBLIC"],
)
