load("//buck2:haskell.bzl", "haskell_library")

haskell_library(
    name = "scip-indexer",
    srcs = [
        "Glean/Indexer/SCIP.hs",
    ],
    deps = [
        "@hsthrift//common/util:fb-util",
        "//glean/client/hs:client-hs",
        "//glean/index:indexer-core",
        "//glean/lang/scip:scip",
        "//glean/lib:lib-derive",
    ],
    packages = [
        "directory",
        "optparse-applicative",
        "temporary",
        "text",
    ],
    visibility = ["PUBLIC"],
)
