load("//buck2:haskell.bzl", "haskell_library")

# Cabal's `test-lib` library (glean.cabal.in). MakeTestDB.hs also lives in
# this directory but isn't in glean.cabal.in's exposed-modules and isn't
# referenced from anywhere else in glean.cabal.in either - left out, same
# as every other unreferenced file elsewhere in this migration.
haskell_library(
    name = "test-lib",
    srcs = [
        "TestBatch.hs",
        "TestDB.hs",
        "TestData.hs",
        "Glean/Database/Catalog/Test.hs",
        "Glean/Database/Test.hs",
    ],
    deps = [
        "//hsthrift/common/util:fb-util",
        "//glean/angle:angle",
        "//glean/backend-api:backend-api",
        "//glean/backend-local:backend-local",
        "//glean/hs:core",
        "//glean/db:db",
        "//glean/config:config",
        "//glean/if:if-glean-hs",
        "//glean/if:if-internal-hs",
        "//glean/github:stubs",
        "//glean/test/unit:test-unit",
        "//glean/typed:typed",
        "//glean/util:util",
        "//glean/schema/thrift:cxx1",
        "//glean/schema/thrift:src",
        "//glean/schema/thrift:glean_test",
        "//glean/schema/thrift:sys",
        "//glean/schema/hs:cxx1",
        "//glean/schema/hs:src",
        "//glean/schema/hs:glean_test",
        "//glean/schema/hs:sys",
    ],
    visibility = ["PUBLIC"],
)
