load("//buck2:haskell.bzl", "haskell_library")

haskell_library(
    name = "bench-util",
    srcs = [
        "Glean/Util/Benchmark.hs",
    ],
    deps = [
        "//glean/github:stubs",
    ],
    packages = [
        "criterion",
    ],
    visibility = ["PUBLIC"],
)
