load("//buck2:cxx.bzl", "cxx_library")
load("//buck2:haskell.bzl", "haskell_binary", "haskell_library")

cxx_library(
    name = "bytecode-cpp",
    exported_headers = [
        "evaluate.h",
        "instruction.h",
    ],
    visibility = ["PUBLIC"],
)

haskell_library(
    name = "bytecode",
    srcs = [
        "Glean/Bytecode/Types.hs",
        "Glean/Bytecode/Decode.hs",
        "Glean/Bytecode/SysCalls.hs",
    ],
    packages = [
        "mtl",
        "text",
        "transformers",
    ],
    visibility = ["PUBLIC"],
)

haskell_library(
    name = "bytecode-instruction",
    srcs = {
        "Glean/Bytecode/Generate/Instruction.hs": "def/Glean/Bytecode/Generate/Instruction.hs",
    },
    deps = [":bytecode"],
    packages = [
        "text",
    ],
    visibility = ["PUBLIC"],
)

haskell_binary(
    name = "gen-bytecode-hs",
    srcs = {
        "Glean/Bytecode/Generate/Haskell.hs": "gen/Glean/Bytecode/Generate/Haskell.hs",
    },
    main = "Glean.Bytecode.Generate.Haskell",
    deps = [
        ":bytecode",
        ":bytecode-instruction",
    ],
    packages = [
        "directory",
        "filepath",
        "text",
    ],
    visibility = ["PUBLIC"],
)

genrule(
    name = "gen-bytecode",
    cmd = "$(exe :gen-bytecode-hs) --install_dir=$OUT",
    outs = {
        "Instruction.hs": ["Glean/RTS/Bytecode/Gen/Instruction.hs"],
        "Issue.hs": ["Glean/RTS/Bytecode/Gen/Issue.hs"],
        "Version.hs": ["Glean/RTS/Bytecode/Gen/Version.hs"],
    },
    visibility = ["PUBLIC"],
)
