load("//buck2:cxx.bzl", "cxx_library")

# Cabal's `storage` library (glean.cabal.in): thin storage-backend
# abstraction sitting on top of //glean/rts:rts. Same shape/reasoning as
# glean/rts/BUCK (repo-root-relative includes, -DOSS=1 for the same
# `#ifdef OSS` / <cpp/memory.h> vs <common/hs/util/cpp/memory.h> split) -
# see that file's comment for the full explanation.
cxx_library(
    name = "storage",
    srcs = [
        "ffi.cpp",
        "stats.cpp",
    ],
    exported_headers = [
        "common.h",
        "db.h",
        "ffi.h",
        "stats.h",
    ],
    compiler_flags = ["-DOSS=1"],
    deps = [
        "//hsthrift/common/util:fb-util-cxx",
        "//hsthrift/folly-clib:folly-clib",
        "//glean/rts:rts",
    ],
    visibility = ["PUBLIC"],
)
