load("//buck2:cxx.bzl", "cxx_library")

cxx_library(
    name = "storage",
    srcs = [
        "ffi.cpp",
        "stats.cpp",
    ],
    exported_headers = [
        "common.h",
        "db.h",
        "ffi.h",
        "stats.h",
    ],
    compiler_flags = ["-DOSS=1"],
    deps = [
        "@hsthrift//common/util:fb-util-cxx",
        "@hsthrift//folly-clib:folly-clib",
        "//glean/rts:rts",
    ],
    visibility = ["PUBLIC"],
)
