// @generated SignedSource<<71d6ff8f4d3cf6e738c89fc5ac245d43>>
// DO NOT EDIT THIS FILE MANUALLY!
// This file is a mechanical copy of the version in the configerator repo. To
// modify it, edit the copy in the configerator repo instead and copy it over by
// running the following in your fbcode directory:
//
// configerator-thrift-updater glean/recipes/recipes.thrift

// Copyright (c) Facebook, Inc. and its affiliates.

namespace hs Glean
namespace java.swift com.facebook.glean.recipes
namespace py glean.recipes
namespace py3 glean
namespace php glean_recipes
namespace cpp2 glean.recipes
namespace rust glean_recipes

typedef string TaskName

enum Executor {
  WorkQueue = 0,
  External = 1,
  Manual = 2
}

struct Recipe {
  # Names of tasks that this recipe depends on
  2: set<TaskName> dependencies = [];

  # Number of work parcels to split the task into
  3: i32 parcels = 1;

  # How often should a parcel be retried
  4: i32 retries = 2;

  # How often should a worker ping the server (in seconds)
  5: i32 heartbeat = 60;

  # Executor for the task
  8: Executor executor = WorkQueue;

  # Arbitrary worker-specific settings
  7: map<string,string> settings = {};

  # DEPRECATED
  6: string worker = "";
}

typedef map<TaskName, Recipe> Recipes

struct Config {
  # Recipes for populating databases (repo -> recipes)
  1: map<string, Recipes> recipes;
}
