load("//buck2:cxx.bzl", "cxx_library")

# Cabal's `rocksdb` library (glean.cabal.in): storage backend on top of
# //glean/storage:storage and //glean/rts:rts. -fno-rtti matches Cabal's
# cxx-options exactly (RocksDB's own headers are commonly built/used
# without RTTI). container-impl.cpp's `#ifdef GLEAN_FACEBOOK` branch
# (a real Meta-internal rocksdb wrapper, glean/facebook/rocksdb/rocksdb.h -
# doesn't exist in this checkout) is excluded since we never define
# GLEAN_FACEBOOK, same idea as -DOSS=1 elsewhere but a different macro.
cxx_library(
    name = "rocksdb",
    srcs = [
        "container-impl.cpp",
        "database-impl.cpp",
        "ffi.cpp",
        "rocksdb.cpp",
    ],
    # `headers` not `exported_headers`: nothing outside this package
    # includes these, unlike glean/rts's or glean/storage's headers.
    headers = [
        "container-impl.h",
        "database-impl.h",
        "ffi.h",
        "rocksdb.h",
        "util.h",
    ],
    compiler_flags = ["-DOSS=1", "-fno-rtti"],
    exported_linker_flags = [
        "-lrocksdb",
    ],
    deps = [
        "@hsthrift//common/util:fb-util-cxx",
        "@hsthrift//folly-clib:folly-clib",
        "//glean/rts:rts",
        "//glean/storage:storage",
    ],
    visibility = ["PUBLIC"],
)
