-- @generated
module Glean.Schema.Hack (allPredicates) where

import Glean.Types

allPredicates :: [(PredicateRef, Int)]
allPredicates =
  [ (PredicateRef "hack.ClassDeclaration" 4, 480)
  , (PredicateRef "hack.QName" 4, 472)
  , (PredicateRef "hack.TargetUses" 4, 466)
  , (PredicateRef "hack.filename" 1, 457)
  , (PredicateRef "hack.TargetUsesAbs" 4, 451)
  , (PredicateRef "hack.TraitDefinition" 4, 411)
  , (PredicateRef "hack.DeclarationName" 4, 396)
  , (PredicateRef "hack.FunctionDefinition" 4, 389)
  , (PredicateRef "hack.PropertyDeclaration" 4, 384)
  , (PredicateRef "hack.PropertyDefinition" 4, 355)
  , (PredicateRef "hack.ContainerChild" 4, 347)
  , (PredicateRef "hack.symbolNamespace" 1, 341)
  , (PredicateRef "hack.UserAttribute" 4, 337)
  , (PredicateRef "hack.DeclarationSource" 4, 332)
  , (PredicateRef "hack.NamespaceQName" 4, 324)
  , (PredicateRef "hack.InterfaceDeclaration" 4, 323)
  , (PredicateRef "hack.kind" 1, 321)
  , (PredicateRef "hack.InterfaceDefinition" 4, 306)
  , (PredicateRef "hack.Comment" 4, 289)
  , (PredicateRef "hack.identifier" 1, 288)
  , (PredicateRef "hack.NamespaceMember" 4, 279)
  , (PredicateRef "hack.ContainerParent" 4, 268)
  , (PredicateRef "hack.GlobalConstDefinition" 4, 266)
  , (PredicateRef "hack.EnumDefinition" 4, 258)
  , (PredicateRef "hack.symbol" 1, 257)
  , (PredicateRef "hack.ClassConstDefinition" 4, 254)
  , (PredicateRef "hack.GlobalConstDeclaration" 4, 248)
  , (PredicateRef "hack.DeclarationTarget" 4, 225)
  , (PredicateRef "hack.FileXRefs" 4, 212)
  , (PredicateRef "hack.DeclarationSpan" 4, 209)
  , (PredicateRef "hack.Enumerator" 4, 193)
  , (PredicateRef "hack.Signature" 4, 187)
  , (PredicateRef "hack.TypedefDeclaration" 4, 182)
  , (PredicateRef "hack.Name" 4, 181)
  , (PredicateRef "hack.MethodDeclaration" 4, 163)
  , (PredicateRef "hack.TraitDeclaration" 4, 146)
  , (PredicateRef "hack.FunctionDeclaration" 4, 139)
  , (PredicateRef "hack.MethodDefinition" 4, 120)
  , (PredicateRef "hack.FileDeclarations" 4, 101)
  , (PredicateRef "hack.DeclarationLocation" 4, 95)
  , (PredicateRef "hack.TypeConstDeclaration" 4, 94)
  , (PredicateRef "hack.NameLowerCase" 4, 56)
  , (PredicateRef "hack.TypeConstDefinition" 4, 52)
  , (PredicateRef "hack.Type" 4, 49)
  , (PredicateRef "hack.DeclarationComment" 4, 43)
  , (PredicateRef "hack.ClassConstDeclaration" 4, 34)
  , (PredicateRef "hack.EnumDeclaration" 4, 27)
  , (PredicateRef "hack.NamespaceDeclaration" 4, 19)
  , (PredicateRef "hack.ClassDefinition" 4, 1)
  ]

