-- @generated
module Glean.Schema.Hack (allPredicates) where

import Glean.Types

allPredicates :: [(PredicateRef, Int)]
allPredicates =
  [ (PredicateRef "hack.ClassDeclaration" 4, 488)
  , (PredicateRef "hack.QName" 4, 480)
  , (PredicateRef "hack.TargetUses" 4, 474)
  , (PredicateRef "hack.filename" 1, 465)
  , (PredicateRef "hack.TargetUsesAbs" 4, 459)
  , (PredicateRef "hack.TraitDefinition" 4, 419)
  , (PredicateRef "hack.DeclarationName" 4, 404)
  , (PredicateRef "hack.FunctionDefinition" 4, 397)
  , (PredicateRef "hack.PropertyDeclaration" 4, 392)
  , (PredicateRef "hack.PropertyDefinition" 4, 361)
  , (PredicateRef "hack.ContainerChild" 4, 352)
  , (PredicateRef "hack.symbolNamespace" 1, 345)
  , (PredicateRef "hack.UserAttribute" 4, 341)
  , (PredicateRef "hack.DeclarationSource" 4, 336)
  , (PredicateRef "hack.NamespaceQName" 4, 328)
  , (PredicateRef "hack.InterfaceDeclaration" 4, 327)
  , (PredicateRef "hack.kind" 1, 325)
  , (PredicateRef "hack.InterfaceDefinition" 4, 310)
  , (PredicateRef "hack.Comment" 4, 293)
  , (PredicateRef "hack.identifier" 1, 292)
  , (PredicateRef "hack.NamespaceMember" 4, 283)
  , (PredicateRef "hack.ContainerParent" 4, 272)
  , (PredicateRef "hack.GlobalConstDefinition" 4, 270)
  , (PredicateRef "hack.EnumDefinition" 4, 262)
  , (PredicateRef "hack.symbol" 1, 261)
  , (PredicateRef "hack.ClassConstDefinition" 4, 258)
  , (PredicateRef "hack.GlobalConstDeclaration" 4, 252)
  , (PredicateRef "hack.DeclarationTarget" 4, 227)
  , (PredicateRef "hack.FileXRefs" 4, 213)
  , (PredicateRef "hack.DeclarationSpan" 4, 210)
  , (PredicateRef "hack.Enumerator" 4, 194)
  , (PredicateRef "hack.Signature" 4, 188)
  , (PredicateRef "hack.TypedefDeclaration" 4, 183)
  , (PredicateRef "hack.Name" 4, 182)
  , (PredicateRef "hack.MethodDeclaration" 4, 164)
  , (PredicateRef "hack.TraitDeclaration" 4, 147)
  , (PredicateRef "hack.FunctionDeclaration" 4, 140)
  , (PredicateRef "hack.MethodDefinition" 4, 121)
  , (PredicateRef "hack.FileDeclarations" 4, 102)
  , (PredicateRef "hack.DeclarationLocation" 4, 96)
  , (PredicateRef "hack.TypeConstDeclaration" 4, 95)
  , (PredicateRef "hack.NameLowerCase" 4, 56)
  , (PredicateRef "hack.TypeConstDefinition" 4, 52)
  , (PredicateRef "hack.Type" 4, 49)
  , (PredicateRef "hack.DeclarationComment" 4, 43)
  , (PredicateRef "hack.ClassConstDeclaration" 4, 34)
  , (PredicateRef "hack.EnumDeclaration" 4, 27)
  , (PredicateRef "hack.NamespaceDeclaration" 4, 19)
  , (PredicateRef "hack.ClassDefinition" 4, 1)
  ]

