-- @generated
module Glean.Schema.Python (allPredicates) where

import Glean.Types

allPredicates :: [(PredicateRef, Int)]
allPredicates =
  [ (PredicateRef "python.ClassDefinition" 2, 501)
  , (PredicateRef "python.ImportStatementByName" 2, 466)
  , (PredicateRef "python.DeclarationToName" 2, 462)
  , (PredicateRef "python.DeclarationByName" 2, 458)
  , (PredicateRef "python.DocstringContent" 2, 443)
  , (PredicateRef "python.VariableBySName" 2, 435)
  , (PredicateRef "python.FileDirectXRefs" 2, 434)
  , (PredicateRef "python.FunctionDeclaration" 1, 412)
  , (PredicateRef "python.DirectXRefsByFile" 2, 396)
  , (PredicateRef "python.FunctionDefinition" 2, 369)
  , (PredicateRef "python.DeclarationUses" 2, 355)
  , (PredicateRef "python.ImportStatement" 2, 332)
  , (PredicateRef "python.ImportStatement" 1, 331)
  , (PredicateRef "python.DeclarationLocation" 2, 322)
  , (PredicateRef "python.DeclarationLocation" 1, 321)
  , (PredicateRef "python.ModuleBySName" 2, 320)
  , (PredicateRef "python.ClassDeclaration" 1, 273)
  , (PredicateRef "python.VariableDefinition" 2, 266)
  , (PredicateRef "python.FileXRefs" 2, 242)
  , (PredicateRef "python.FileXRefs" 1, 241)
  , (PredicateRef "python.SName" 2, 231)
  , (PredicateRef "python.TargetUses" 2, 203)
  , (PredicateRef "python.TargetUses" 1, 202)
  , (PredicateRef "python.ClassBySName" 2, 189)
  , (PredicateRef "python.XRefIndirectTarget" 2, 168)
  , (PredicateRef "python.XRefIndirectTarget" 1, 167)
  , (PredicateRef "python.Module" 1, 165)
  , (PredicateRef "python.DeclarationBySName" 2, 144)
  , (PredicateRef "python.Name" 1, 130)
  , (PredicateRef "python.ModuleDefinition" 2, 122)
  , (PredicateRef "python.SNameToName" 2, 103)
  , (PredicateRef "python.NameToSName" 2, 98)
  , (PredicateRef "python.Type" 1, 80)
  , (PredicateRef "python.DeclarationWithName" 2, 69)
  , (PredicateRef "python.FunctionBySName" 2, 62)
  , (PredicateRef "python.ImportStatementByAsSName" 3, 60)
  , (PredicateRef "python.ImportStatementByAsSName" 2, 59)
  , (PredicateRef "python.VariableDeclaration" 1, 23)
  , (PredicateRef "python.DeclarationsByFile" 2, 21)
  , (PredicateRef "python.XRefsViaNameByFile" 2, 20)
  , (PredicateRef "python.ImportStatementByAsName" 3, 8)
  , (PredicateRef "python.ImportStatementByAsName" 2, 7)
  ]

