load("//buck2:cxx.bzl", "cxx_library")

cxx_library(
    name = "client-cpp",
    srcs = [
        "filewriter.cpp",
        "glean.cpp",
    ],
    exported_headers = [
        "filewriter.h",
        "glean.h",
        "sender.h",
    ],
    compiler_flags = ["-DOSS=1"],
    deps = [
        "@hsthrift//common/util:fb-util-cxx",
        "@hsthrift//folly-clib:folly-clib",
        "//glean/rts:rts",
    ],
    visibility = ["PUBLIC"],
)
