load("//buck2:haskell.bzl", "haskell_library")

haskell_library(
    name = "lsif",
    srcs = [
        "Data/LSIF/Angle.hs",
        "Data/LSIF/Env.hs",
        "Data/LSIF/Gen.hs",
        "Data/LSIF/JSON.hs",
        "Data/LSIF/Moniker.hs",
        "Data/LSIF/Types.hs",
        "Glean/LSIF/Driver.hs",
    ],
    deps = [
        "@hsthrift//common/util:fb-util",
    ],
    packages = [
        "aeson",
        "bytestring",
        "containers",
        "directory",
        "extra",
        "filepath",
        "mtl",
        "process",
        "split",
        "temporary",
        "text",
        "vector",
    ],
    visibility = ["PUBLIC"],
)
