-- @generated
module Glean.Schema.Python (allPredicates) where

import Glean.Types

allPredicates :: [(PredicateRef, Int)]
allPredicates =
  [ (PredicateRef "python.ClassDefinition" 2, 506)
  , (PredicateRef "python.ImportStatementByName" 2, 471)
  , (PredicateRef "python.DeclarationToName" 2, 467)
  , (PredicateRef "python.DeclarationByName" 2, 463)
  , (PredicateRef "python.DocstringContent" 2, 448)
  , (PredicateRef "python.VariableBySName" 2, 440)
  , (PredicateRef "python.FileDirectXRefs" 2, 439)
  , (PredicateRef "python.FunctionDeclaration" 1, 417)
  , (PredicateRef "python.DirectXRefsByFile" 2, 401)
  , (PredicateRef "python.FunctionDefinition" 2, 374)
  , (PredicateRef "python.DeclarationUses" 2, 360)
  , (PredicateRef "python.ImportStatement" 2, 337)
  , (PredicateRef "python.ImportStatement" 1, 336)
  , (PredicateRef "python.DeclarationLocation" 2, 327)
  , (PredicateRef "python.DeclarationLocation" 1, 326)
  , (PredicateRef "python.ModuleBySName" 2, 325)
  , (PredicateRef "python.ClassDeclaration" 1, 276)
  , (PredicateRef "python.VariableDefinition" 2, 269)
  , (PredicateRef "python.FileXRefs" 2, 245)
  , (PredicateRef "python.FileXRefs" 1, 244)
  , (PredicateRef "python.SName" 2, 234)
  , (PredicateRef "python.TargetUses" 2, 205)
  , (PredicateRef "python.TargetUses" 1, 204)
  , (PredicateRef "python.ClassBySName" 2, 190)
  , (PredicateRef "python.XRefIndirectTarget" 2, 169)
  , (PredicateRef "python.XRefIndirectTarget" 1, 168)
  , (PredicateRef "python.Module" 1, 166)
  , (PredicateRef "python.DeclarationBySName" 2, 145)
  , (PredicateRef "python.Name" 1, 131)
  , (PredicateRef "python.ModuleDefinition" 2, 123)
  , (PredicateRef "python.SNameToName" 2, 104)
  , (PredicateRef "python.NameToSName" 2, 99)
  , (PredicateRef "python.Type" 1, 81)
  , (PredicateRef "python.DeclarationWithName" 2, 70)
  , (PredicateRef "python.FunctionBySName" 2, 63)
  , (PredicateRef "python.ImportStatementByAsSName" 3, 61)
  , (PredicateRef "python.ImportStatementByAsSName" 2, 60)
  , (PredicateRef "python.ContainingTopLevelDeclaration" 3, 47)
  , (PredicateRef "python.VariableDeclaration" 1, 23)
  , (PredicateRef "python.DeclarationsByFile" 2, 21)
  , (PredicateRef "python.XRefsViaNameByFile" 2, 20)
  , (PredicateRef "python.ImportStatementByAsName" 3, 8)
  , (PredicateRef "python.ImportStatementByAsName" 2, 7)
  ]

