-- @generated
module Glean.Schema.Thrift (allPredicates) where

import Glean.Types

allPredicates :: [(PredicateRef, Int)]
allPredicates =
  [ (PredicateRef "thrift.ServiceName" 2, 492)
  , (PredicateRef "thrift.FunctionName" 2, 469)
  , (PredicateRef "thrift.TypeSpecification" 3, 461)
  , (PredicateRef "thrift.MangleLang" 1, 442)
  , (PredicateRef "thrift.ExceptionName" 2, 426)
  , (PredicateRef "thrift.UnionType" 3, 422)
  , (PredicateRef "thrift.Identifier" 1, 421)
  , (PredicateRef "thrift.HackMethod" 1, 395)
  , (PredicateRef "thrift.OutputTarget" 3, 389)
  , (PredicateRef "thrift.QualName" 2, 380)
  , (PredicateRef "thrift.File" 2, 379)
  , (PredicateRef "thrift.HackName" 1, 374)
  , (PredicateRef "thrift.Constant" 2, 373)
  , (PredicateRef "thrift.PythonFunction" 1, 370)
  , (PredicateRef "thrift.IncludeStatement" 2, 356)
  , (PredicateRef "thrift.PythonClassContains" 1, 348)
  , (PredicateRef "thrift.TargetX" 2, 342)
  , (PredicateRef "thrift.NamespaceName" 1, 331)
  , (PredicateRef "thrift.HackRecord" 1, 318)
  , (PredicateRef "thrift.FromCpp2" 1, 306)
  , (PredicateRef "thrift.FromHack" 1, 302)
  , (PredicateRef "thrift.ExceptionType" 4, 296)
  , (PredicateRef "thrift.TypeDefType" 3, 295)
  , (PredicateRef "thrift.FunctionSpecification" 4, 293)
  , (PredicateRef "thrift.FunctionSpecification" 3, 292)
  , (PredicateRef "thrift.ToPython" 1, 281)
  , (PredicateRef "thrift.FromPython" 1, 263)
  , (PredicateRef "thrift.ToCpp2" 1, 258)
  , (PredicateRef "thrift.PythonClass" 1, 252)
  , (PredicateRef "thrift.ToHack" 1, 247)
  , (PredicateRef "thrift.IncludeSpecial" 2, 241)
  , (PredicateRef "thrift.PythonModuleContains" 1, 221)
  , (PredicateRef "thrift.NamedDecl" 2, 220)
  , (PredicateRef "thrift.HackMap" 1, 218)
  , (PredicateRef "thrift.ServiceDefinition" 4, 217)
  , (PredicateRef "thrift.ServiceDefinition" 3, 216)
  , (PredicateRef "thrift.NamespaceValue" 1, 214)
  , (PredicateRef "thrift.PythonModuleFile" 1, 208)
  , (PredicateRef "thrift.EnumValue" 2, 203)
  , (PredicateRef "thrift.TypeDefException" 4, 196)
  , (PredicateRef "thrift.CompileTarget" 3, 191)
  , (PredicateRef "thrift.PythonFileModule" 1, 187)
  , (PredicateRef "thrift.PythonName" 1, 178)
  , (PredicateRef "thrift.Namespace" 2, 167)
  , (PredicateRef "thrift.PythonMethod" 1, 158)
  , (PredicateRef "thrift.PythonModule" 1, 138)
  , (PredicateRef "thrift.ConstantType" 3, 137)
  , (PredicateRef "thrift.FileError" 2, 136)
  , (PredicateRef "thrift.PythonField" 1, 134)
  , (PredicateRef "thrift.EnumerationType" 3, 116)
  , (PredicateRef "thrift.FileOutput" 3, 84)
  , (PredicateRef "thrift.ServiceParent" 2, 80)
  , (PredicateRef "thrift.FileXRefs" 2, 72)
  , (PredicateRef "thrift.IncludeSplice" 2, 68)
  , (PredicateRef "thrift.Lang" 1, 54)
  , (PredicateRef "thrift.Mangle" 1, 48)
  , (PredicateRef "thrift.ServiceChild" 2, 41)
  , (PredicateRef "thrift.EnumValueDef" 3, 36)
  , (PredicateRef "thrift.HackRecordContains" 1, 35)
  , (PredicateRef "thrift.PythonValue" 1, 30)
  , (PredicateRef "thrift.StructType" 3, 28)
  , (PredicateRef "thrift.Includes" 2, 17)
  , (PredicateRef "thrift.FileTarget" 3, 12)
  ]

