load("//buck2:haskell.bzl", "haskell_library")

haskell_library(
    name = "rust-scip-indexer",
    srcs = [
        "Glean/Indexer/RustScip.hs",
    ],
    deps = [
        "@hsthrift//common/util:fb-util",
        "//glean/index:indexer-core",
        "//glean/lang/scip:scip",
        "//glean/lang/scip/indexer:scip-indexer",
    ],
    packages = [
        "optparse-applicative",
    ],
    visibility = ["PUBLIC"],
)
