-- @generated
module Glean.Schema.Cxx1 (allPredicates) where

import Glean.Types

allPredicates :: [(PredicateRef, Int)]
allPredicates =
  [ (PredicateRef "cxx1.NamespaceQName" 1, 501)
  , (PredicateRef "cxx1.DeclarationSrcRange" 4, 500)
  , (PredicateRef "cxx1.RecordDeclaration" 1, 496)
  , (PredicateRef "cxx1.XRefIndirectTarget" 2, 471)
  , (PredicateRef "cxx1.DeclByName" 4, 470)
  , (PredicateRef "cxx1.DeclInObjcContainer" 4, 462)
  , (PredicateRef "cxx1.DeclarationTargets" 1, 452)
  , (PredicateRef "cxx1.ObjcContainerInheritance" 4, 432)
  , (PredicateRef "cxx1.ObjcPropertyIVar" 4, 426)
  , (PredicateRef "cxx1.FunctionDefinition" 1, 424)
  , (PredicateRef "cxx1.TranslationUnitXRefs" 4, 423)
  , (PredicateRef "cxx1.Signature" 1, 415)
  , (PredicateRef "cxx1.Attribute" 4, 412)
  , (PredicateRef "cxx1.DeclInRecord" 4, 404)
  , (PredicateRef "cxx1.FileXRefs" 2, 394)
  , (PredicateRef "cxx1.ObjcSelector" 1, 388)
  , (PredicateRef "cxx1.NamespaceDefinition" 2, 350)
  , (PredicateRef "cxx1.FunctionAttribute" 4, 345)
  , (PredicateRef "cxx1.TypeAliasDeclaration" 2, 343)
  , (PredicateRef "cxx1.FileXRefMap" 2, 325)
  , (PredicateRef "cxx1.EnumDeclaration" 1, 320)
  , (PredicateRef "cxx1.ObjcContainerDeclaration" 1, 317)
  , (PredicateRef "cxx1.ObjcMethodDeclaration" 1, 316)
  , (PredicateRef "cxx1.MethodOverrides" 1, 295)
  , (PredicateRef "cxx1.ObjcInterfaceToImplementation" 1, 278)
  , (PredicateRef "cxx1.FunctionName" 1, 255)
  , (PredicateRef "cxx1.Same" 2, 241)
  , (PredicateRef "cxx1.FunctionDeclaration" 1, 224)
  , (PredicateRef "cxx1.Name" 1, 212)
  , (PredicateRef "cxx1.DeclImpliesRecord" 4, 182)
  , (PredicateRef "cxx1.FunctionQName" 1, 170)
  , (PredicateRef "cxx1.TranslationUnitTrace" 3, 163)
  , (PredicateRef "cxx1.Enumerator" 1, 160)
  , (PredicateRef "cxx1.ObjcPropertyImplementation" 1, 151)
  , (PredicateRef "cxx1.Trace" 2, 146)
  , (PredicateRef "cxx1.MethodOverridden" 4, 143)
  , (PredicateRef "cxx1.TargetUses" 2, 135)
  , (PredicateRef "cxx1.UsingDirective" 2, 133)
  , (PredicateRef "cxx1.DeclFamilyOf" 4, 126)
  , (PredicateRef "cxx1.PPTrace" 2, 125)
  , (PredicateRef "cxx1.QName" 1, 115)
  , (PredicateRef "cxx1.VariableDeclaration" 2, 110)
  , (PredicateRef "cxx1.DeclarationSources" 1, 109)
  , (PredicateRef "cxx1.ObjcContainerBase" 4, 108)
  , (PredicateRef "cxx1.UsingDeclaration" 2, 106)
  , (PredicateRef "cxx1.ObjcMethodDefinition" 1, 92)
  , (PredicateRef "cxx1.DeclarationInTrace" 4, 91)
  , (PredicateRef "cxx1.ObjcContainerDefinition" 2, 88)
  , (PredicateRef "cxx1.EnumDefinition" 1, 85)
  , (PredicateRef "cxx1.Declarations" 2, 78)
  , (PredicateRef "cxx1.DeclToFamily" 2, 65)
  , (PredicateRef "cxx1.NamespaceDeclaration" 1, 62)
  , (PredicateRef "cxx1.DeclarationComment" 1, 58)
  , (PredicateRef "cxx1.ObjcPropertyDeclaration" 1, 56)
  , (PredicateRef "cxx1.RecordDefinition" 2, 46)
  , (PredicateRef "cxx1.ObjcImplements" 1, 39)
  , (PredicateRef "cxx1.EnumeratorInEnum" 4, 37)
  , (PredicateRef "cxx1.DeclFamily" 2, 13)
  , (PredicateRef "cxx1.Type" 1, 9)
  , (PredicateRef "cxx1.RecordDerived" 4, 2)
  ]

