-- @generated
module Glean.Schema.Cxx1 (allPredicates) where

import Glean.Types

allPredicates :: [(PredicateRef, Int)]
allPredicates =
  [ (PredicateRef "cxx1.NamespaceQName" 1, 494)
  , (PredicateRef "cxx1.DeclarationSrcRange" 4, 493)
  , (PredicateRef "cxx1.RecordDeclaration" 1, 490)
  , (PredicateRef "cxx1.XRefIndirectTarget" 2, 465)
  , (PredicateRef "cxx1.DeclByName" 4, 464)
  , (PredicateRef "cxx1.DeclInObjcContainer" 4, 456)
  , (PredicateRef "cxx1.DeclarationTargets" 1, 446)
  , (PredicateRef "cxx1.ObjcContainerInheritance" 4, 426)
  , (PredicateRef "cxx1.ObjcPropertyIVar" 4, 420)
  , (PredicateRef "cxx1.FunctionDefinition" 1, 418)
  , (PredicateRef "cxx1.TranslationUnitXRefs" 4, 417)
  , (PredicateRef "cxx1.Signature" 1, 409)
  , (PredicateRef "cxx1.Attribute" 4, 406)
  , (PredicateRef "cxx1.DeclInRecord" 4, 398)
  , (PredicateRef "cxx1.FileXRefs" 2, 388)
  , (PredicateRef "cxx1.ObjcSelector" 1, 382)
  , (PredicateRef "cxx1.NamespaceDefinition" 2, 346)
  , (PredicateRef "cxx1.FunctionAttribute" 4, 342)
  , (PredicateRef "cxx1.TypeAliasDeclaration" 2, 340)
  , (PredicateRef "cxx1.FileXRefMap" 2, 322)
  , (PredicateRef "cxx1.EnumDeclaration" 1, 317)
  , (PredicateRef "cxx1.ObjcContainerDeclaration" 1, 314)
  , (PredicateRef "cxx1.ObjcMethodDeclaration" 1, 313)
  , (PredicateRef "cxx1.MethodOverrides" 1, 292)
  , (PredicateRef "cxx1.ObjcInterfaceToImplementation" 1, 275)
  , (PredicateRef "cxx1.FunctionName" 1, 252)
  , (PredicateRef "cxx1.Same" 2, 238)
  , (PredicateRef "cxx1.FunctionDeclaration" 1, 222)
  , (PredicateRef "cxx1.Name" 1, 210)
  , (PredicateRef "cxx1.DeclImpliesRecord" 4, 180)
  , (PredicateRef "cxx1.FunctionQName" 1, 168)
  , (PredicateRef "cxx1.TranslationUnitTrace" 3, 161)
  , (PredicateRef "cxx1.Enumerator" 1, 158)
  , (PredicateRef "cxx1.ObjcPropertyImplementation" 1, 149)
  , (PredicateRef "cxx1.Trace" 2, 144)
  , (PredicateRef "cxx1.MethodOverridden" 4, 141)
  , (PredicateRef "cxx1.TargetUses" 2, 133)
  , (PredicateRef "cxx1.UsingDirective" 2, 131)
  , (PredicateRef "cxx1.DeclFamilyOf" 4, 124)
  , (PredicateRef "cxx1.PPTrace" 2, 123)
  , (PredicateRef "cxx1.QName" 1, 113)
  , (PredicateRef "cxx1.VariableDeclaration" 2, 108)
  , (PredicateRef "cxx1.DeclarationSources" 1, 107)
  , (PredicateRef "cxx1.ObjcContainerBase" 4, 106)
  , (PredicateRef "cxx1.UsingDeclaration" 2, 104)
  , (PredicateRef "cxx1.ObjcMethodDefinition" 1, 90)
  , (PredicateRef "cxx1.DeclarationInTrace" 4, 89)
  , (PredicateRef "cxx1.ObjcContainerDefinition" 2, 87)
  , (PredicateRef "cxx1.EnumDefinition" 1, 84)
  , (PredicateRef "cxx1.Declarations" 2, 77)
  , (PredicateRef "cxx1.DeclToFamily" 2, 64)
  , (PredicateRef "cxx1.NamespaceDeclaration" 1, 61)
  , (PredicateRef "cxx1.DeclarationComment" 1, 57)
  , (PredicateRef "cxx1.ObjcPropertyDeclaration" 1, 55)
  , (PredicateRef "cxx1.RecordDefinition" 2, 46)
  , (PredicateRef "cxx1.ObjcImplements" 1, 39)
  , (PredicateRef "cxx1.EnumeratorInEnum" 4, 37)
  , (PredicateRef "cxx1.DeclFamily" 2, 13)
  , (PredicateRef "cxx1.Type" 1, 9)
  , (PredicateRef "cxx1.RecordDerived" 4, 2)
  ]

