-- @generated
module Glean.Schema.Cxx1 (allPredicates) where

import Glean.Types

allPredicates :: [(PredicateRef, Int)]
allPredicates =
  [ (PredicateRef "cxx1.NamespaceQName" 1, 500)
  , (PredicateRef "cxx1.DeclarationSrcRange" 4, 499)
  , (PredicateRef "cxx1.RecordDeclaration" 1, 495)
  , (PredicateRef "cxx1.XRefIndirectTarget" 2, 470)
  , (PredicateRef "cxx1.DeclByName" 4, 469)
  , (PredicateRef "cxx1.DeclInObjcContainer" 4, 461)
  , (PredicateRef "cxx1.DeclarationTargets" 1, 451)
  , (PredicateRef "cxx1.ObjcContainerInheritance" 4, 431)
  , (PredicateRef "cxx1.ObjcPropertyIVar" 4, 425)
  , (PredicateRef "cxx1.FunctionDefinition" 1, 423)
  , (PredicateRef "cxx1.TranslationUnitXRefs" 4, 422)
  , (PredicateRef "cxx1.Signature" 1, 414)
  , (PredicateRef "cxx1.Attribute" 4, 411)
  , (PredicateRef "cxx1.DeclInRecord" 4, 403)
  , (PredicateRef "cxx1.FileXRefs" 2, 393)
  , (PredicateRef "cxx1.ObjcSelector" 1, 387)
  , (PredicateRef "cxx1.NamespaceDefinition" 2, 349)
  , (PredicateRef "cxx1.FunctionAttribute" 4, 344)
  , (PredicateRef "cxx1.TypeAliasDeclaration" 2, 342)
  , (PredicateRef "cxx1.FileXRefMap" 2, 324)
  , (PredicateRef "cxx1.EnumDeclaration" 1, 319)
  , (PredicateRef "cxx1.ObjcContainerDeclaration" 1, 316)
  , (PredicateRef "cxx1.ObjcMethodDeclaration" 1, 315)
  , (PredicateRef "cxx1.MethodOverrides" 1, 294)
  , (PredicateRef "cxx1.ObjcInterfaceToImplementation" 1, 277)
  , (PredicateRef "cxx1.FunctionName" 1, 254)
  , (PredicateRef "cxx1.Same" 2, 240)
  , (PredicateRef "cxx1.FunctionDeclaration" 1, 223)
  , (PredicateRef "cxx1.Name" 1, 211)
  , (PredicateRef "cxx1.DeclImpliesRecord" 4, 181)
  , (PredicateRef "cxx1.FunctionQName" 1, 169)
  , (PredicateRef "cxx1.TranslationUnitTrace" 3, 162)
  , (PredicateRef "cxx1.Enumerator" 1, 159)
  , (PredicateRef "cxx1.ObjcPropertyImplementation" 1, 150)
  , (PredicateRef "cxx1.Trace" 2, 145)
  , (PredicateRef "cxx1.MethodOverridden" 4, 142)
  , (PredicateRef "cxx1.TargetUses" 2, 134)
  , (PredicateRef "cxx1.UsingDirective" 2, 132)
  , (PredicateRef "cxx1.DeclFamilyOf" 4, 125)
  , (PredicateRef "cxx1.PPTrace" 2, 124)
  , (PredicateRef "cxx1.QName" 1, 114)
  , (PredicateRef "cxx1.VariableDeclaration" 2, 109)
  , (PredicateRef "cxx1.DeclarationSources" 1, 108)
  , (PredicateRef "cxx1.ObjcContainerBase" 4, 107)
  , (PredicateRef "cxx1.UsingDeclaration" 2, 105)
  , (PredicateRef "cxx1.ObjcMethodDefinition" 1, 91)
  , (PredicateRef "cxx1.DeclarationInTrace" 4, 90)
  , (PredicateRef "cxx1.ObjcContainerDefinition" 2, 87)
  , (PredicateRef "cxx1.EnumDefinition" 1, 84)
  , (PredicateRef "cxx1.Declarations" 2, 77)
  , (PredicateRef "cxx1.DeclToFamily" 2, 64)
  , (PredicateRef "cxx1.NamespaceDeclaration" 1, 61)
  , (PredicateRef "cxx1.DeclarationComment" 1, 57)
  , (PredicateRef "cxx1.ObjcPropertyDeclaration" 1, 55)
  , (PredicateRef "cxx1.RecordDefinition" 2, 46)
  , (PredicateRef "cxx1.ObjcImplements" 1, 39)
  , (PredicateRef "cxx1.EnumeratorInEnum" 4, 37)
  , (PredicateRef "cxx1.DeclFamily" 2, 13)
  , (PredicateRef "cxx1.Type" 1, 9)
  , (PredicateRef "cxx1.RecordDerived" 4, 2)
  ]

