-- @generated
module Glean.Schema.Hack (allPredicates) where

import Glean.Types

allPredicates :: [(PredicateRef, Int)]
allPredicates =
  [ (PredicateRef "hack.ClassDeclaration" 4, 489)
  , (PredicateRef "hack.QName" 4, 481)
  , (PredicateRef "hack.TargetUses" 4, 475)
  , (PredicateRef "hack.filename" 1, 466)
  , (PredicateRef "hack.TargetUsesAbs" 4, 460)
  , (PredicateRef "hack.TraitDefinition" 4, 420)
  , (PredicateRef "hack.DeclarationName" 4, 405)
  , (PredicateRef "hack.FunctionDefinition" 4, 398)
  , (PredicateRef "hack.PropertyDeclaration" 4, 393)
  , (PredicateRef "hack.PropertyDefinition" 4, 362)
  , (PredicateRef "hack.ContainerChild" 4, 353)
  , (PredicateRef "hack.symbolNamespace" 1, 346)
  , (PredicateRef "hack.UserAttribute" 4, 342)
  , (PredicateRef "hack.DeclarationSource" 4, 337)
  , (PredicateRef "hack.NamespaceQName" 4, 329)
  , (PredicateRef "hack.InterfaceDeclaration" 4, 328)
  , (PredicateRef "hack.kind" 1, 326)
  , (PredicateRef "hack.InterfaceDefinition" 4, 311)
  , (PredicateRef "hack.Comment" 4, 294)
  , (PredicateRef "hack.identifier" 1, 293)
  , (PredicateRef "hack.NamespaceMember" 4, 284)
  , (PredicateRef "hack.ContainerParent" 4, 273)
  , (PredicateRef "hack.GlobalConstDefinition" 4, 271)
  , (PredicateRef "hack.EnumDefinition" 4, 263)
  , (PredicateRef "hack.symbol" 1, 262)
  , (PredicateRef "hack.ClassConstDefinition" 4, 259)
  , (PredicateRef "hack.GlobalConstDeclaration" 4, 253)
  , (PredicateRef "hack.DeclarationTarget" 4, 228)
  , (PredicateRef "hack.FileXRefs" 4, 214)
  , (PredicateRef "hack.DeclarationSpan" 4, 211)
  , (PredicateRef "hack.Enumerator" 4, 195)
  , (PredicateRef "hack.Signature" 4, 189)
  , (PredicateRef "hack.TypedefDeclaration" 4, 184)
  , (PredicateRef "hack.Name" 4, 183)
  , (PredicateRef "hack.MethodDeclaration" 4, 165)
  , (PredicateRef "hack.TraitDeclaration" 4, 148)
  , (PredicateRef "hack.FunctionDeclaration" 4, 141)
  , (PredicateRef "hack.MethodDefinition" 4, 122)
  , (PredicateRef "hack.FileDeclarations" 4, 103)
  , (PredicateRef "hack.DeclarationLocation" 4, 97)
  , (PredicateRef "hack.TypeConstDeclaration" 4, 96)
  , (PredicateRef "hack.NameLowerCase" 4, 57)
  , (PredicateRef "hack.TypeConstDefinition" 4, 53)
  , (PredicateRef "hack.Type" 4, 50)
  , (PredicateRef "hack.DeclarationComment" 4, 43)
  , (PredicateRef "hack.ClassConstDeclaration" 4, 34)
  , (PredicateRef "hack.EnumDeclaration" 4, 27)
  , (PredicateRef "hack.NamespaceDeclaration" 4, 19)
  , (PredicateRef "hack.ClassDefinition" 4, 1)
  ]

