-- @generated
module Glean.Schema.Hack (allPredicates) where

import Glean.Types

allPredicates :: [(PredicateRef, Int)]
allPredicates =
  [ (PredicateRef "hack.ClassDeclaration" 4, 483)
  , (PredicateRef "hack.QName" 4, 475)
  , (PredicateRef "hack.TargetUses" 4, 469)
  , (PredicateRef "hack.filename" 1, 460)
  , (PredicateRef "hack.TargetUsesAbs" 4, 454)
  , (PredicateRef "hack.TraitDefinition" 4, 414)
  , (PredicateRef "hack.DeclarationName" 4, 399)
  , (PredicateRef "hack.FunctionDefinition" 4, 392)
  , (PredicateRef "hack.PropertyDeclaration" 4, 387)
  , (PredicateRef "hack.PropertyDefinition" 4, 357)
  , (PredicateRef "hack.ContainerChild" 4, 349)
  , (PredicateRef "hack.symbolNamespace" 1, 343)
  , (PredicateRef "hack.UserAttribute" 4, 339)
  , (PredicateRef "hack.DeclarationSource" 4, 334)
  , (PredicateRef "hack.NamespaceQName" 4, 326)
  , (PredicateRef "hack.InterfaceDeclaration" 4, 325)
  , (PredicateRef "hack.kind" 1, 323)
  , (PredicateRef "hack.InterfaceDefinition" 4, 308)
  , (PredicateRef "hack.Comment" 4, 291)
  , (PredicateRef "hack.identifier" 1, 290)
  , (PredicateRef "hack.NamespaceMember" 4, 281)
  , (PredicateRef "hack.ContainerParent" 4, 270)
  , (PredicateRef "hack.GlobalConstDefinition" 4, 268)
  , (PredicateRef "hack.EnumDefinition" 4, 260)
  , (PredicateRef "hack.symbol" 1, 259)
  , (PredicateRef "hack.ClassConstDefinition" 4, 256)
  , (PredicateRef "hack.GlobalConstDeclaration" 4, 250)
  , (PredicateRef "hack.DeclarationTarget" 4, 226)
  , (PredicateRef "hack.FileXRefs" 4, 212)
  , (PredicateRef "hack.DeclarationSpan" 4, 209)
  , (PredicateRef "hack.Enumerator" 4, 193)
  , (PredicateRef "hack.Signature" 4, 187)
  , (PredicateRef "hack.TypedefDeclaration" 4, 182)
  , (PredicateRef "hack.Name" 4, 181)
  , (PredicateRef "hack.MethodDeclaration" 4, 163)
  , (PredicateRef "hack.TraitDeclaration" 4, 146)
  , (PredicateRef "hack.FunctionDeclaration" 4, 139)
  , (PredicateRef "hack.MethodDefinition" 4, 120)
  , (PredicateRef "hack.FileDeclarations" 4, 101)
  , (PredicateRef "hack.DeclarationLocation" 4, 95)
  , (PredicateRef "hack.TypeConstDeclaration" 4, 94)
  , (PredicateRef "hack.NameLowerCase" 4, 56)
  , (PredicateRef "hack.TypeConstDefinition" 4, 52)
  , (PredicateRef "hack.Type" 4, 49)
  , (PredicateRef "hack.DeclarationComment" 4, 43)
  , (PredicateRef "hack.ClassConstDeclaration" 4, 34)
  , (PredicateRef "hack.EnumDeclaration" 4, 27)
  , (PredicateRef "hack.NamespaceDeclaration" 4, 19)
  , (PredicateRef "hack.ClassDefinition" 4, 1)
  ]

