-- @generated
module Glean.Schema.Thrift (allPredicates) where

import Glean.Types

allPredicates :: [(PredicateRef, Int)]
allPredicates =
  [ (PredicateRef "thrift.ServiceName" 2, 486)
  , (PredicateRef "thrift.FunctionName" 2, 464)
  , (PredicateRef "thrift.TypeSpecification" 3, 456)
  , (PredicateRef "thrift.MangleLang" 1, 437)
  , (PredicateRef "thrift.ExceptionName" 2, 421)
  , (PredicateRef "thrift.UnionType" 3, 417)
  , (PredicateRef "thrift.Identifier" 1, 416)
  , (PredicateRef "thrift.HackMethod" 1, 390)
  , (PredicateRef "thrift.OutputTarget" 3, 384)
  , (PredicateRef "thrift.QualName" 2, 375)
  , (PredicateRef "thrift.File" 2, 374)
  , (PredicateRef "thrift.HackName" 1, 369)
  , (PredicateRef "thrift.Constant" 2, 368)
  , (PredicateRef "thrift.PythonFunction" 1, 366)
  , (PredicateRef "thrift.IncludeStatement" 2, 352)
  , (PredicateRef "thrift.PythonClassContains" 1, 344)
  , (PredicateRef "thrift.TargetX" 2, 338)
  , (PredicateRef "thrift.NamespaceName" 1, 327)
  , (PredicateRef "thrift.HackRecord" 1, 314)
  , (PredicateRef "thrift.FromCpp2" 1, 302)
  , (PredicateRef "thrift.FromHack" 1, 298)
  , (PredicateRef "thrift.TypeDefType" 3, 292)
  , (PredicateRef "thrift.FunctionSpecification" 3, 290)
  , (PredicateRef "thrift.ToPython" 1, 279)
  , (PredicateRef "thrift.FromPython" 1, 261)
  , (PredicateRef "thrift.ToCpp2" 1, 256)
  , (PredicateRef "thrift.PythonClass" 1, 250)
  , (PredicateRef "thrift.ToHack" 1, 245)
  , (PredicateRef "thrift.IncludeSpecial" 2, 239)
  , (PredicateRef "thrift.PythonModuleContains" 1, 219)
  , (PredicateRef "thrift.NamedDecl" 2, 218)
  , (PredicateRef "thrift.HackMap" 1, 216)
  , (PredicateRef "thrift.ServiceDefinition" 3, 215)
  , (PredicateRef "thrift.NamespaceValue" 1, 213)
  , (PredicateRef "thrift.PythonModuleFile" 1, 207)
  , (PredicateRef "thrift.EnumValue" 2, 202)
  , (PredicateRef "thrift.CompileTarget" 3, 191)
  , (PredicateRef "thrift.PythonFileModule" 1, 187)
  , (PredicateRef "thrift.PythonName" 1, 178)
  , (PredicateRef "thrift.Namespace" 2, 167)
  , (PredicateRef "thrift.PythonMethod" 1, 158)
  , (PredicateRef "thrift.PythonModule" 1, 138)
  , (PredicateRef "thrift.ConstantType" 3, 137)
  , (PredicateRef "thrift.FileError" 2, 136)
  , (PredicateRef "thrift.PythonField" 1, 134)
  , (PredicateRef "thrift.EnumerationType" 3, 116)
  , (PredicateRef "thrift.FileOutput" 3, 84)
  , (PredicateRef "thrift.ServiceParent" 2, 80)
  , (PredicateRef "thrift.FileXRefs" 2, 72)
  , (PredicateRef "thrift.IncludeSplice" 2, 68)
  , (PredicateRef "thrift.Lang" 1, 54)
  , (PredicateRef "thrift.Mangle" 1, 48)
  , (PredicateRef "thrift.ServiceChild" 2, 41)
  , (PredicateRef "thrift.EnumValueDef" 3, 36)
  , (PredicateRef "thrift.HackRecordContains" 1, 35)
  , (PredicateRef "thrift.PythonValue" 1, 30)
  , (PredicateRef "thrift.StructType" 3, 28)
  , (PredicateRef "thrift.Includes" 2, 17)
  , (PredicateRef "thrift.FileTarget" 3, 12)
  ]

