-- @generated
module Glean.Schema.Thrift (allPredicates) where

import Glean.Types

allPredicates :: [(PredicateRef, Int)]
allPredicates =
  [ (PredicateRef "thrift.ServiceName" 2, 485)
  , (PredicateRef "thrift.FunctionName" 2, 463)
  , (PredicateRef "thrift.TypeSpecification" 3, 455)
  , (PredicateRef "thrift.MangleLang" 1, 436)
  , (PredicateRef "thrift.ExceptionName" 2, 420)
  , (PredicateRef "thrift.UnionType" 3, 416)
  , (PredicateRef "thrift.Identifier" 1, 415)
  , (PredicateRef "thrift.HackMethod" 1, 389)
  , (PredicateRef "thrift.OutputTarget" 3, 383)
  , (PredicateRef "thrift.QualName" 2, 374)
  , (PredicateRef "thrift.File" 2, 373)
  , (PredicateRef "thrift.HackName" 1, 368)
  , (PredicateRef "thrift.Constant" 2, 367)
  , (PredicateRef "thrift.PythonFunction" 1, 365)
  , (PredicateRef "thrift.IncludeStatement" 2, 351)
  , (PredicateRef "thrift.PythonClassContains" 1, 343)
  , (PredicateRef "thrift.TargetX" 2, 337)
  , (PredicateRef "thrift.NamespaceName" 1, 326)
  , (PredicateRef "thrift.HackRecord" 1, 313)
  , (PredicateRef "thrift.FromCpp2" 1, 301)
  , (PredicateRef "thrift.FromHack" 1, 297)
  , (PredicateRef "thrift.TypeDefType" 3, 291)
  , (PredicateRef "thrift.FunctionSpecification" 3, 289)
  , (PredicateRef "thrift.ToPython" 1, 278)
  , (PredicateRef "thrift.FromPython" 1, 260)
  , (PredicateRef "thrift.ToCpp2" 1, 255)
  , (PredicateRef "thrift.PythonClass" 1, 249)
  , (PredicateRef "thrift.ToHack" 1, 244)
  , (PredicateRef "thrift.IncludeSpecial" 2, 238)
  , (PredicateRef "thrift.PythonModuleContains" 1, 218)
  , (PredicateRef "thrift.NamedDecl" 2, 217)
  , (PredicateRef "thrift.HackMap" 1, 215)
  , (PredicateRef "thrift.ServiceDefinition" 3, 214)
  , (PredicateRef "thrift.NamespaceValue" 1, 212)
  , (PredicateRef "thrift.PythonModuleFile" 1, 206)
  , (PredicateRef "thrift.EnumValue" 2, 201)
  , (PredicateRef "thrift.CompileTarget" 3, 190)
  , (PredicateRef "thrift.PythonFileModule" 1, 186)
  , (PredicateRef "thrift.PythonName" 1, 177)
  , (PredicateRef "thrift.Namespace" 2, 166)
  , (PredicateRef "thrift.PythonMethod" 1, 157)
  , (PredicateRef "thrift.PythonModule" 1, 137)
  , (PredicateRef "thrift.ConstantType" 3, 136)
  , (PredicateRef "thrift.FileError" 2, 135)
  , (PredicateRef "thrift.PythonField" 1, 133)
  , (PredicateRef "thrift.EnumerationType" 3, 115)
  , (PredicateRef "thrift.FileOutput" 3, 83)
  , (PredicateRef "thrift.ServiceParent" 2, 79)
  , (PredicateRef "thrift.FileXRefs" 2, 71)
  , (PredicateRef "thrift.IncludeSplice" 2, 67)
  , (PredicateRef "thrift.Lang" 1, 53)
  , (PredicateRef "thrift.Mangle" 1, 47)
  , (PredicateRef "thrift.ServiceChild" 2, 41)
  , (PredicateRef "thrift.EnumValueDef" 3, 36)
  , (PredicateRef "thrift.HackRecordContains" 1, 35)
  , (PredicateRef "thrift.PythonValue" 1, 30)
  , (PredicateRef "thrift.StructType" 3, 28)
  , (PredicateRef "thrift.Includes" 2, 17)
  , (PredicateRef "thrift.FileTarget" 3, 12)
  ]

