-- @generated
module Glean.Schema.Thrift (allPredicates) where

import Glean.Types

allPredicates :: [(PredicateRef, Int)]
allPredicates =
  [ (PredicateRef "thrift.ServiceName" 2, 478)
  , (PredicateRef "thrift.FunctionName" 2, 456)
  , (PredicateRef "thrift.TypeSpecification" 3, 448)
  , (PredicateRef "thrift.MangleLang" 1, 429)
  , (PredicateRef "thrift.ExceptionName" 2, 413)
  , (PredicateRef "thrift.UnionType" 3, 409)
  , (PredicateRef "thrift.Identifier" 1, 408)
  , (PredicateRef "thrift.HackMethod" 1, 382)
  , (PredicateRef "thrift.OutputTarget" 3, 376)
  , (PredicateRef "thrift.QualName" 2, 367)
  , (PredicateRef "thrift.File" 2, 366)
  , (PredicateRef "thrift.HackName" 1, 362)
  , (PredicateRef "thrift.Constant" 2, 361)
  , (PredicateRef "thrift.PythonFunction" 1, 359)
  , (PredicateRef "thrift.IncludeStatement" 2, 346)
  , (PredicateRef "thrift.PythonClassContains" 1, 339)
  , (PredicateRef "thrift.TargetX" 2, 333)
  , (PredicateRef "thrift.NamespaceName" 1, 322)
  , (PredicateRef "thrift.HackRecord" 1, 309)
  , (PredicateRef "thrift.FromCpp2" 1, 297)
  , (PredicateRef "thrift.FromHack" 1, 293)
  , (PredicateRef "thrift.TypeDefType" 3, 287)
  , (PredicateRef "thrift.FunctionSpecification" 3, 285)
  , (PredicateRef "thrift.ToPython" 1, 274)
  , (PredicateRef "thrift.FromPython" 1, 256)
  , (PredicateRef "thrift.ToCpp2" 1, 251)
  , (PredicateRef "thrift.PythonClass" 1, 245)
  , (PredicateRef "thrift.ToHack" 1, 240)
  , (PredicateRef "thrift.IncludeSpecial" 2, 234)
  , (PredicateRef "thrift.PythonModuleContains" 1, 217)
  , (PredicateRef "thrift.NamedDecl" 2, 216)
  , (PredicateRef "thrift.HackMap" 1, 214)
  , (PredicateRef "thrift.ServiceDefinition" 3, 213)
  , (PredicateRef "thrift.NamespaceValue" 1, 211)
  , (PredicateRef "thrift.PythonModuleFile" 1, 205)
  , (PredicateRef "thrift.EnumValue" 2, 200)
  , (PredicateRef "thrift.CompileTarget" 3, 189)
  , (PredicateRef "thrift.PythonFileModule" 1, 185)
  , (PredicateRef "thrift.PythonName" 1, 176)
  , (PredicateRef "thrift.Namespace" 2, 165)
  , (PredicateRef "thrift.PythonMethod" 1, 156)
  , (PredicateRef "thrift.PythonModule" 1, 136)
  , (PredicateRef "thrift.ConstantType" 3, 135)
  , (PredicateRef "thrift.FileError" 2, 134)
  , (PredicateRef "thrift.PythonField" 1, 132)
  , (PredicateRef "thrift.EnumerationType" 3, 114)
  , (PredicateRef "thrift.FileOutput" 3, 83)
  , (PredicateRef "thrift.ServiceParent" 2, 79)
  , (PredicateRef "thrift.FileXRefs" 2, 71)
  , (PredicateRef "thrift.IncludeSplice" 2, 67)
  , (PredicateRef "thrift.Lang" 1, 53)
  , (PredicateRef "thrift.Mangle" 1, 47)
  , (PredicateRef "thrift.ServiceChild" 2, 41)
  , (PredicateRef "thrift.EnumValueDef" 3, 36)
  , (PredicateRef "thrift.HackRecordContains" 1, 35)
  , (PredicateRef "thrift.PythonValue" 1, 30)
  , (PredicateRef "thrift.StructType" 3, 28)
  , (PredicateRef "thrift.Includes" 2, 17)
  , (PredicateRef "thrift.FileTarget" 3, 12)
  ]

