load("//buck2:haskell.bzl", "haskell_library")

# Cabal's `indexers` library includes this module (Glean.Indexer.Erlang)
# among its 18 - see glean/index/BUCK's comment for the split rationale.
haskell_library(
    name = "erlang-indexer",
    srcs = [
        "Glean/Indexer/Erlang.hs",
    ],
    deps = [
        "@hsthrift//common/util:fb-util",
        "//glean/index:indexer-core",
    ],
    packages = [
        "optparse-applicative",
    ],
    visibility = ["PUBLIC"],
)
