load("//buck2:haskell.bzl", "haskell_library")

# Cabal's `indexers` library includes this module (Glean.Indexer.Cpp) among
# its 18 - see glean/index/BUCK's comment for the split rationale. The
# heaviest of the 14 language indexers: uses Glean.Interprocess.Worklist to
# parallelise indexing work (see glean/interprocess/cpp/BUCK's comment for
# why interprocess was split off client-cpp specifically because of this).
haskell_library(
    name = "clang-indexer",
    srcs = [
        "Glean/Indexer/Cpp.hs",
    ],
    deps = [
        "//hsthrift/common/util:fb-util",
        "//hsthrift/http:thrift-http",
        "//hsthrift/lib:thrift-lib",
        "//glean/client/hs:client-hs",
        "//glean/client/hs/local:client-hs-local",
        "//glean/index:indexer-core",
        "//glean/interprocess/hs:interprocess",
        "//glean/server:handler",
        "//glean/github/if:if-fb303-hs",
        "//glean/github:stubs",
        "//glean/util:util",
    ],
    packages = [
        "aeson",
        "ansi-terminal",
        "async",
        "bytestring",
        "directory",
        "filepath",
        "optparse-applicative",
        "process",
        "text",
    ],
    visibility = ["PUBLIC"],
)
