load("//buck2:haskell.bzl", "haskell_test")

# Cabal's `glean-snapshot-typescript` test-suite (glean.cabal.in).
haskell_test(
    name = "glean-snapshot-typescript",
    main = "Glean.Regression.TypeScript.Main",
    srcs = [
        "Glean/Regression/TypeScript/Main.hs",
    ],
    deps = [
        "//glean/lang/typescript:typescript-indexer",
        "//glean/test/regression:regression-test-lib",
    ],
    visibility = ["PUBLIC"],
)
