load("//buck2:haskell.bzl", "haskell_library")

haskell_library(
    name = "indexer-core",
    srcs = [
        "Glean/Indexer.hs",
        "Glean/Indexer/External.hs",
    ],
    deps = [
        "@hsthrift//common/util:fb-util",
        "@hsthrift//http:thrift-http",
        "//glean/client/hs:client-hs",
        "//glean/client/hs/local:client-hs-local",
        "//glean/lib:lib-derive",
        "//glean/server:handler",
        "//glean/github/if:if-fb303-hs",
        "//glean/github:stubs",
        "//glean/util:util",
    ],
    packages = [
        "aeson",
        "extra",
        "directory",
        "filepath",
        "process",
        "temporary",
        "text",
        "optparse-applicative",
        "unordered-containers",
    ],
    visibility = ["PUBLIC"],
)
