load("//buck2:haskell.bzl", "haskell_library")

haskell_library(
    name = "cli-types",
    srcs = [
        "GleanCLI/Types.hs",
        "GleanCLI/Utils.hs",
    ],
    deps = [
        "@hsthrift//common/util:fb-util",
        "//glean/client/hs/local:client-hs-local",
        "//glean/config:config",
        "//glean/db:db",
        "//glean/util:util",
    ],
    packages = [
        "optparse-applicative",
    ],
    visibility = ["PUBLIC"],
)
