// @generated SignedSource<<0bc36b78454c609db88220a7b5fceccc>>
// DO NOT EDIT THIS FILE MANUALLY!
// This file is a mechanical copy of the version in the configerator repo. To
// modify it, edit the copy in the configerator repo instead and copy it over by
// running the following in your fbcode directory:
//
// configerator-thrift-updater glean/client/client_config.thrift
// Copyright (c) Facebook, Inc. and its affiliates.

namespace cpp2 facebook.glean
namespace hs Glean
namespace py glean.client_config
namespace py3 glean
namespace php glean
namespace rust glean_client_config

include "glean/config/service.thrift"

// Strategy to find a Glean query server with the desired db.
// The name 'UseShards' is a historic implementation detail: Glean query servers
// reuse the sharding mechanism to advertise which dbs they currently serve.
enum UseShards {
  // Ask for a random Glean query server
  NO_SHARDS = 0,
  // Ask for a query server that can serve the selected db
  USE_SHARDS = 1,
  // Ask for a specific server, falling back to arbitary server
  USE_SHARDS_AND_FALLBACK = 2,
} (hs.prefix = "", hs.nounknown)

struct ClientConfig {
  1: service.Service serv = {"tier": "glean.query.prod"};
  // The default tier to connect to

  2: UseShards use_shards = USE_SHARDS_AND_FALLBACK;
  // The strategy to select a Glean server

  3: i32 min_db_age = 1800;
  // DEPRECATED

  4: i32 host_timeout_ms = 30000;
  // The timeout to use when we connect to a Glean server using an
  // explicit host:port, otherwise Thrift defaults to 100ms.

  5: i32 max_batch_size = 1;
  // maximum number of queries to include in a batch request,
  // a value of 1 or lower will disable batching
}
