load("//buck2:haskell.bzl", "haskell_binary", "haskell_library")

haskell_library(
    name = "sharding",
    srcs = [
        "Glean/Server/Config.hs",
        "Glean/Server/Sharding.hs",
    ],
    deps = [
        "@hsthrift//common/util:fb-util",
        "//glean/backend-api:backend-api",
        "//glean/backend-local:backend-local",
        "//glean/config:config",
        "//glean/db:db",
        "//glean/if:if-glean-hs",
        "//glean/github:stubs",
        "//glean/util:util",
    ],
    visibility = ["PUBLIC"],
)

haskell_library(
    name = "handler",
    srcs = [
        "Glean/Handler.hs",
    ],
    deps = [
        "@hsthrift//common/util:fb-util",
        "//glean/backend-local:backend-local",
        "//glean/client/hs:client-hs",
        "//glean/github/if:if-fb303-hs",
        "//glean/if:if-glean-hs",
        "//glean/github:stubs",
        "//glean/db:db",
        "//glean/config:config",
    ],
    visibility = ["PUBLIC"],
)

haskell_binary(
    name = "glean-server",
    main = "Glean.Server",
    compiler_flags = ["-XCPP"],
    srcs = [
        "Glean/Handler.hs",
        "Glean/Server.hs",
    ],
    deps = [
        "@hsthrift//common/util:fb-util",
        "@hsthrift//http:thrift-http",
        "//glean/backend-local:backend-local",
        "//glean/client/hs:client-hs",
        "//glean/github/if:if-fb303-hs",
        "//glean/if:if-glean-hs",
        "//glean/if:if-index-hs",
        "//glean/github:stubs",
        "//glean/config:config",
        "//glean/hs:core",
        "//glean/db:db",
        "//glean/util:util",
        ":sharding",
    ],
    packages = [
        "haskeline",
        "json",
    ],
    visibility = ["PUBLIC"],
)
