load("//buck2:cxx.bzl", "cxx_library")

# Cabal's `lmdb` library (glean.cabal.in): storage backend on top of
# //glean/storage:storage, //glean/rts:rts and the vendored
# //glean/lmdb-clib:lmdb-clib (for lmdb.h/mdb.c/midl.c - see that BUCK
# file).
cxx_library(
    name = "lmdb",
    srcs = [
        "container-impl.cpp",
        "database-impl.cpp",
        "ffi.cpp",
        "glean_lmdb.cpp",
    ],
    # `headers` not `exported_headers`: nothing outside this package
    # includes these, unlike glean/rts's or glean/storage's headers.
    headers = [
        "container-impl.h",
        "database-impl.h",
        "ffi.h",
        "glean_lmdb.h",
        "util.h",
    ],
    compiler_flags = ["-DOSS=1"],
    deps = [
        "@hsthrift//common/util:fb-util-cxx",
        "@hsthrift//folly-clib:folly-clib",
        "//glean/lmdb-clib:lmdb-clib",
        "//glean/rts:rts",
        "//glean/storage:storage",
    ],
    visibility = ["PUBLIC"],
)
