load("//buck2:cxx.bzl", "cxx_library")

# Cabal's `lmdb` library (glean.cabal.in): storage backend on top of
# //glean/storage:storage, //glean/rts:rts and the vendored
# //glean/lmdb-clib:lmdb-clib (for lmdb.h/mdb.c/midl.c - see that BUCK
# file).
cxx_library(
    name = "lmdb",
    srcs = [
        "container-impl.cpp",
        "database-impl.cpp",
        "ffi.cpp",
        "glean_lmdb.cpp",
    ],
    compiler_flags = ["-std=c++20", "-march=haswell", "-DOSS=1"],
    include_directories = ["../.."],
    public_include_directories = ["../.."],
    deps = [
        "//hsthrift/common/util:fb-util-cxx",
        "//hsthrift/folly-clib:folly-clib",
        "//glean/lmdb-clib:lmdb-clib",
        "//glean/rts:rts",
        "//glean/storage:storage",
    ],
    visibility = ["PUBLIC"],
)
