load("//buck2:haskell.bzl", "haskell_library")

# Cabal's `indexers` library includes this module (Glean.Indexer.PythonScip)
# among its 18 - see glean/index/BUCK's comment for the split rationale.
haskell_library(
    name = "python-scip-indexer",
    srcs = [
        "Glean/Indexer/PythonScip.hs",
    ],
    deps = [
        "//hsthrift/common/util:fb-util",
        "//glean/index:indexer-core",
        "//glean/lang/scip:scip",
        "//glean/lang/scip/indexer:scip-indexer",
    ],
    packages = [
        "optparse-applicative",
    ],
    visibility = ["PUBLIC"],
)
