// @generated SignedSource<<2706f09ce8a3bc08af3357a7bfe79b87>>
// DO NOT EDIT THIS FILE MANUALLY!
// This file is a mechanical copy of the version in the configerator repo. To
// modify it, edit the copy in the configerator repo instead and copy it over by
// running the following in your fbcode directory:
//
// configerator-thrift-updater glean/lang/clang/indexer_config.thrift

namespace hs Glean
namespace php glean

struct Options {
  /// Include (transitive) dependencies of specified targets
  1: bool includeDependencies = true;
}

/// A BlockIten is either locator ending in "/..." or a regular expression
/// matching full locators. These should start with the buck cell as "cell//".
typedef string BlockItem

/// Configure the Glean clang indexer (fbsource/fbcode/glean/lang/clang)
struct Config {
  1: list<string> targetBlacklist = [];
  2: map<string, Options> subdirOptions = {};
  3: map<string, list<BlockItem>> blockLists = {};
}
