load("//buck2:haskell.bzl", "haskell_library")
load("//buck2:thrift.bzl", "thrift_library")
# Cabal's `if-auth-hs` library (glean.cabal.in).
haskell_library(
    name = "if-auth-hs",
    srcs = thrift_library(
        name = "if-auth-hs",
        thrift_files = {
        "auth.thrift": ["Glean/Auth/Auth/Types.hs"],
    },
        thrift_flags = ["-I", "."],
    ),
    deps = [
        "//hsthrift/common/util:fb-util",
        "//hsthrift/lib:thrift-lib",
        "//thrift/annotation:thrift-annotation",
    ],
    packages = [
        "aeson",
        "bytestring",
        "containers",
        "data-default",
        "deepseq",
        "ghc-prim",
        "hashable",
        "STMonadTrans",
        "text",
        "unordered-containers",
        "vector",
    ],
    visibility = ["PUBLIC"],
)
