load("//buck2:haskell.bzl", "haskell_library")
load("//buck2:thrift.bzl", "thrift_srcs")
# Cabal's `thrift-annotation` library (glean.cabal.in): the standard Thrift
# annotation IDLs, generated to Haskell. cpp/haskell/hack/rust/thrift.thrift
# all `include "thrift/annotation/scope.thrift"` (and cpp/haskell also
# thrift.thrift) - every file below sees every other one automatically,
# since they're all in the same thrift_files dict (see thrift_srcs()'s own
# comment in buck2/thrift.bzl).
haskell_library(
    name = "thrift-annotation",
    srcs = thrift_srcs(
        name = "thrift-annotation",
        thrift_files = {
        "scope.thrift": ["Scope/Types.hs"],
        "thrift.thrift": ["Facebook/Thrift/Annotation/Thrift/Thrift/Types.hs"],
        "haskell.thrift": ["Facebook/Thrift/Annotation/Haskell/Haskell/Types.hs"],
        "cpp.thrift": ["Facebook/Thrift/Annotation/Cpp/Cpp/Types.hs"],
        "hack.thrift": ["Hack/Types.hs"],
        "rust.thrift": ["Rust/Types.hs"],
    },
        full_paths = True,
    ),
    deps = [
        "@hsthrift//common/util:fb-util",
        "@hsthrift//lib:thrift-lib",
    ],
    packages = [
        "aeson",
        "bytestring",
        "containers",
        "data-default",
        "deepseq",
        "ghc-prim",
        "hashable",
        "STMonadTrans",
        "text",
        "unordered-containers",
        "vector",
    ],
    visibility = ["PUBLIC"],
)
