load("//buck2:haskell.bzl", "haskell_test")

haskell_test(
    name = "glean-snapshot-hack",
    main = "Glean.Regression.Hack.Main",
    srcs = [
        "Glean/Regression/Hack/Main.hs",
    ],
    deps = [
        "//glean/lang/hack:hack-indexer",
        "//glean/test/regression:regression-test-lib",
    ],
    visibility = ["PUBLIC"],
)
