load("//buck2:haskell.bzl", "haskell_library")
load("//buck2:cxx.bzl", "cxx_library")

cxx_library(
    name = "client-hs-cxx",
    srcs = [
        "cpp/write.cpp",
    ],
    deps = [
        "@hsthrift//folly-clib:folly-clib",
    ],
    visibility = ["PUBLIC"],
)

haskell_library(
    name = "client-hs",
    srcs = [
        "Glean.hs",
        "Glean/Angle.hs",
        "Glean/Write.hs",
        "Glean/Haxl.hs",
        "Glean/Remote.hs",
        "Glean/Repo.hs",
        "Glean/Haxl/Repos.hs",
        "Glean/Util/ShellPrint.hs",
    ],
    deps = [
        ":client-hs-cxx",
        "@hsthrift//common/mangle:mangle",
        "@hsthrift//common/util:fb-util",
        "@hsthrift//haxl:thrift-haxl",
        "@hsthrift//lib:thrift-lib",
        "//glean/angle:angle",
        "//glean/backend-api:backend-api",
        "//glean/config:config",
        "//glean/hs:core",
        "//glean/github:defaultconfigs",
        "//glean/haxl:haxl-datasource",
        "//glean/if:if-glean-hs",
        "//glean/github:stubs",
        "//glean/typed:typed",
        "//glean/util:util",
        "//glean/write:write",
    ],
    packages = [
        "aeson",
        "aeson-pretty",
        "bytestring",
        "containers",
        "data-default",
        "extra",
        "haxl",
        "optparse-applicative",
        "prettyprinter-ansi-terminal",
        "process",
        "process-extras",
        "template-haskell",
        "text",
        "time",
        "unordered-containers",
        "vector",
    ],
    visibility = ["PUBLIC"],
)
